bar:
  location: top
  height: 15
  background: 000000ff
  font: DM Mono:size=11

  left:
  - river:
      anchors:
      - base: &river_base
          margin: 30
          text: "{id}"
          on-click: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"

      content:
        map:
          tag: state
          values:
            focused:
              string:
                <<: *river_base
                deco:
                  stack:
                  - background: { color: 0d948dff }

            unfocused:
              string:
                <<: *river_base
            invisible:
              map:
                tag: occupied
                values:
                  true:
                    string:
                      <<: *river_base

                  false:
                    map:
                      tag: id
                      default:
                        empty: {}
                      values:
                        1: { string: { <<: *river_base }}
  right:
  - clock:
      date-format: "%F"
      content:
        string:
          margin: 8
          text: "{date} {time}"

